# Generated by Django 3.0.2 on 2020-01-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zakupki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('cost', models.CharField(max_length=25, verbose_name='Цена')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Парсинг проектов',
                'verbose_name_plural': 'Парсинг проектов',
            },
        ),
    ]
